Repository hashicorp/packer-plugin-oracle, pull requests merged in 2023-01, with the labels that each got.

#73 Add policy documentation
  .gitignore
  docs/builders/oci.mdx
Labels: documentation, enhancement

#72 go.mod: bump go version from 1.17 to 1.18
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: enhancement, tech-debt

#77 Add support for HCP Packer
  builder/classic/artifact.go
  builder/classic/builder.go
  builder/oci/artifact.go
  builder/oci/artifact_test.go
Labels: enhancement

#78 .gitignore: ignore .docs
  .gitignore
Labels: tech-debt

#76 Support setting baseline_ocpu_utilization to allow burstable instances to be launched
  builder/oci/config.go
  builder/oci/config.hcl2spec.go
  builder/oci/driver_oci.go
  docs/builders/oci.mdx
Labels: enhancement
